### ISSUE TITLE
Help Needed with Tensorflow model

### ISSUE THREAD

**Issue by oluwabajio** [VVasanth/Android---Music-Genre-Classifier#1]
Hello,

To be very honest with you, for a long time, i have been following your medium articles about Audio Machine learning especially on Android.
I have read your post multiple times and have understood a lot about audio processing.

Currently, i came across a tflite model i have been having difficulty integrating in my android app. i would really appreciate your help.

Thank you so much.

**Comment by VVasanth** [comment]
Hi Oluwabajio,

Thanks for your kind words...Pls let me know the details of your model and I will see how I could help you.

Thanks,
V.Vasanth

**Comment by oluwabajio** [comment]
Ok, thanks.

I am trying to embed spleeter into a mobile app via tensorflow-lite. (https://github.com/deezer/spleeter)

i couldnt convert the TF models to tflite, but after searching online, i was able to get an already converted tflite model.

Here is the model property - https://ibb.co/hD76dLL

So basically i am supposed to send in an audio and the model is meant to seperate the audio to 2 files (instrumentals & vocals).

My issue is that how do i send the audio to the tensorflowlite and make it return the 2 files. i would really appreciate any help.

I am quite good with kotlin and java.

Thanks for your help.

**Comment by VVasanth** [comment]
Hi Oluwabajio,

Lets take the discussion out of github, as this request is not related to this github project.

I was also trying to build TFLite model out of Spleeter some time back and at that time observed spleeter was built in the earlier version of TF and did not support TFLite conversion. Also, before feeding the audio file to spleeter - it has to be processed with STFT and other processes. I need to check whether jLibrosa supports all the required processing.

Pls respond to my mail and we can continue the discussion over there.

Thanks!

**Comment by oluwabajio** [comment]
Done
